apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: null
  labels:
    app: nginx-replicaset
  name: nginx-replicaset
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-replicaset
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-replicaset
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
