apiVersion: v1
kind: Service
metadata:
  name: yh-service-nodeport
spec:
  type: NodePort
  selector:
    app: feel
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30001
