apiVersion: v1
kind: Pod
metadata:
  name: yh-storage-pod
spec:
  volumes:
    - name: yh-storage
      emptyDir: {}
  containers:
    - name: output-container
      image: busybox
      command: ["/bin/sh", "-c", "echo 'output generated!' > /data/msg; sleep 3600"]
      volumeMounts:
        - name: yh-storage
          mountPath: /data
    - name: input-container
      image: busybox
      command: ["/bin/sh", "-c", "cat/data/msg; sleep 3600"]
      volumeMounts:
        - name: yh-storage
          mountPath: /data

