apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: yh-deployment
  name: yh-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yh-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: yh-deployment
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
