apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx-pod
  name: nginx-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
