apiVersion: v1
kind: Service
metadata:
  name: yh-load-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-pod
  ports:
    - protocol: TCP
      port: 8080 #clusterIP or LoadBalancerIP
      targetPort: 80
      # nodePort: 30001 #skip available
