apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
    - name: write-container
      image: busybox
      command:
        - sh
        - -c
        - echo Hi WriteContainer > /data/msg && sleep 3600
      volumeMounts:
        - mountPath: /data
          name: shared-data
    - name: read-container
      image: busybox
      command:
        - sh
        - -c
        - cat /data/msg && sleep 3600
      volumeMounts:
        - mountPath: /data
          name: shared-data
  volumes:
    - name: shared-data
      emptyDir: {}