apiVersion: v1
kind: Pod
metadata:
  name:  emptydir-example
spec:
  containers:
  - name: app-container
    image: nginx
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
