apiVersion: v1
kind: Pod
metadata:
  name: secret-env-test-volume
spec:
  containers:
   - name: test-container
     image: busybox
     command: ["sleep", "3600"]
     volumeMounts:
      - name: secret-volume
        mountPath: "/etc/secret"
  volumes:
   - name: secret-volume
     secret:
       secretName: my-secret
