apiVersion: v1
kind: Pod
metadata:
  name: secret-env-test
spec:
  containers:
   - name: test-container
     image: busybox
     command: ["sleep", "3600"]
     env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: SECRET_USERNAME
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: SECRET_PASSWORD
