apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  serviceAccountName: my-service-account
  containers:
  - name: test-container
    image: bitnami/kubectl
    command: ["/bin/sh", "-c", "sleep 3600"]
