apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache-web
  name: apache-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache-web
    spec:
      containers:
      - image: httpd:latest
        name: httpd
        resources: {}
status: {}
